<?php
/**
 * @file
 * Code for the Agency Review feature.
 */

include_once 'agency_review.features.inc';

/**
 * Implements hook_pet_substitutions_alter().
 */
function agency_review_pet_substitutions_alter(&$substitutions, $params) {
  if (isset($params['rules_state']) && isset($params['rules_state']->variables['node'])) {
    $node = $params['rules_state']->variables['node']->value();
    $node_edit = $node->nid;
    $substitutions['node'] = $node;
  }
  else {
    return;
  }
}

/**
 * Implements hook_node_access().
 */
function agency_review_node_access($node, $op, $account) {
  if (isset($node->type) && $node->type == 'review') {
    if (in_array('agency_owner', $account->roles)) {
      return NODE_ACCESS_ALLOW;
    }
    else {
      if ($node->status == 0) {
        if (isset($node->field_review_property[LANGUAGE_NONE][0]['target_id'])) {
          drupal_goto('/unit/' . $node->field_review_property[LANGUAGE_NONE][0]['target_id']);
        }
      }
    }
  }
}
