<?php
/**
 * @file
 * Code for the Agency Review feature.
 */

include_once 'agency_review.features.inc';

/**
 * Implements hook_ctools_plugin_directory()
 */
function agency_review_ctools_plugin_directory($owner, $plugin_type) {
  if ($owner == 'ctools' && $plugin_type == 'content_types') {
    return 'plugins/content_types';
  }
}

/**
 * Implements hook_pet_substitutions_alter().
 */
function agency_review_pet_substitutions_alter(&$substitutions, $params) {
  if (isset($params['rules_state']) && isset($params['rules_state']->variables['node'])) {
    $node = $params['rules_state']->variables['node']->value();
    $node_edit = $node->nid;
    $substitutions['node'] = $node;
  }
  else {
    return;
  }
}

/**
 * Implements hook_node_access().
 */
function agency_review_node_access($node, $op, $account) {
  if (isset($node->type) && $node->type == 'review') {
    if (in_array('agency_owner', $account->roles)) {
      return NODE_ACCESS_ALLOW;
    }
    else {
      if ($node->status == 0) {
        if (isset($node->field_review_property[LANGUAGE_NONE][0]['target_id'])) {
          drupal_goto('/unit/' . $node->field_review_property[LANGUAGE_NONE][0]['target_id']);
        }
      }
    }
  }
}

/**
 * Implements hook_form_FORM_ID_alter().
 * FORM_ID = review_node_form.
 */
function agency_review_form_review_node_form_alter(&$form, &$form_state) {
  global $user;

  // Set the right property to review and disable the selection.
  if (isset($_GET['property_id']) && isset($form['field_review_property'])) {
    $form['field_review_property'][LANGUAGE_NONE]['#default_value'] = $_GET['property_id'];
    $form['field_review_property']['#disabled'] = TRUE;
  }
  // Set User mail.
  if (isset($user->mail) && isset($form['field_review_email'])) {
    $form['field_review_email'][LANGUAGE_NONE][0]['email']['#default_value'] = $user->mail;
  }
  // Set User name.
  if (isset($user->name) && isset($form['field_review_name'])) {
    $form['field_review_name'][LANGUAGE_NONE][0]['value']['#default_value'] = $user->name;
  }
}

/**
 * Implements hook_date_formats().
 */
function agency_review_date_formats() {
  return array(
    // Creates a new format for a new, custom format type.
    array(
      'type' => 'agency_review_m_y',
      'format' => 'F Y',
      'locales' => array(),
    ),
  );
}

/**
 * Implements hook_date_format_types().
 */
function agency_review_date_format_types() {
  return array(
    'agency_review_m_y' => t('Month and Year'),
  );
}
